version: '2'
services:
  db:
    image: mysql
    env_file: ./production.env
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  browser-mining:
    build: ./tornado
    command: web
    env_file: ./production.env
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx
    depends_on:
      - browser-mining
    ports:
      - "127.0.0.1:30004:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
