version: '2'
services:
  cyclic-one-time-pad:
    build: ./flask
    restart: always

  nginx:
    image: nginx
    depends_on:
      - cyclic-one-time-pad
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
